//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	kluster "github.com/viveksinghggits/kluster-api/pkg/apis/kluster"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	SchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*KlsuterStatus)(nil), (*kluster.KlsuterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KlsuterStatus_To_kluster_KlsuterStatus(a.(*KlsuterStatus), b.(*kluster.KlsuterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kluster.KlsuterStatus)(nil), (*KlsuterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kluster_KlsuterStatus_To_v1alpha1_KlsuterStatus(a.(*kluster.KlsuterStatus), b.(*KlsuterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Kluster)(nil), (*kluster.Kluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Kluster_To_kluster_Kluster(a.(*Kluster), b.(*kluster.Kluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kluster.Kluster)(nil), (*Kluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kluster_Kluster_To_v1alpha1_Kluster(a.(*kluster.Kluster), b.(*Kluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KlusterList)(nil), (*kluster.KlusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KlusterList_To_kluster_KlusterList(a.(*KlusterList), b.(*kluster.KlusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kluster.KlusterList)(nil), (*KlusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kluster_KlusterList_To_v1alpha1_KlusterList(a.(*kluster.KlusterList), b.(*KlusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KlusterSpec)(nil), (*kluster.KlusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KlusterSpec_To_kluster_KlusterSpec(a.(*KlusterSpec), b.(*kluster.KlusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kluster.KlusterSpec)(nil), (*KlusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kluster_KlusterSpec_To_v1alpha1_KlusterSpec(a.(*kluster.KlusterSpec), b.(*KlusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodePool)(nil), (*kluster.NodePool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodePool_To_kluster_NodePool(a.(*NodePool), b.(*kluster.NodePool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kluster.NodePool)(nil), (*NodePool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kluster_NodePool_To_v1alpha1_NodePool(a.(*kluster.NodePool), b.(*NodePool), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_KlsuterStatus_To_kluster_KlsuterStatus(in *KlsuterStatus, out *kluster.KlsuterStatus, s conversion.Scope) error {
	out.KlusterID = in.KlusterID
	out.Progress = in.Progress
	out.KubeConfig = in.KubeConfig
	return nil
}

// Convert_v1alpha1_KlsuterStatus_To_kluster_KlsuterStatus is an autogenerated conversion function.
func Convert_v1alpha1_KlsuterStatus_To_kluster_KlsuterStatus(in *KlsuterStatus, out *kluster.KlsuterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_KlsuterStatus_To_kluster_KlsuterStatus(in, out, s)
}

func autoConvert_kluster_KlsuterStatus_To_v1alpha1_KlsuterStatus(in *kluster.KlsuterStatus, out *KlsuterStatus, s conversion.Scope) error {
	out.KlusterID = in.KlusterID
	out.Progress = in.Progress
	out.KubeConfig = in.KubeConfig
	return nil
}

// Convert_kluster_KlsuterStatus_To_v1alpha1_KlsuterStatus is an autogenerated conversion function.
func Convert_kluster_KlsuterStatus_To_v1alpha1_KlsuterStatus(in *kluster.KlsuterStatus, out *KlsuterStatus, s conversion.Scope) error {
	return autoConvert_kluster_KlsuterStatus_To_v1alpha1_KlsuterStatus(in, out, s)
}

func autoConvert_v1alpha1_Kluster_To_kluster_Kluster(in *Kluster, out *kluster.Kluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_KlusterSpec_To_kluster_KlusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_KlsuterStatus_To_kluster_KlsuterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Kluster_To_kluster_Kluster is an autogenerated conversion function.
func Convert_v1alpha1_Kluster_To_kluster_Kluster(in *Kluster, out *kluster.Kluster, s conversion.Scope) error {
	return autoConvert_v1alpha1_Kluster_To_kluster_Kluster(in, out, s)
}

func autoConvert_kluster_Kluster_To_v1alpha1_Kluster(in *kluster.Kluster, out *Kluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_kluster_KlusterSpec_To_v1alpha1_KlusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_kluster_KlsuterStatus_To_v1alpha1_KlsuterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_kluster_Kluster_To_v1alpha1_Kluster is an autogenerated conversion function.
func Convert_kluster_Kluster_To_v1alpha1_Kluster(in *kluster.Kluster, out *Kluster, s conversion.Scope) error {
	return autoConvert_kluster_Kluster_To_v1alpha1_Kluster(in, out, s)
}

func autoConvert_v1alpha1_KlusterList_To_kluster_KlusterList(in *KlusterList, out *kluster.KlusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]kluster.Kluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_KlusterList_To_kluster_KlusterList is an autogenerated conversion function.
func Convert_v1alpha1_KlusterList_To_kluster_KlusterList(in *KlusterList, out *kluster.KlusterList, s conversion.Scope) error {
	return autoConvert_v1alpha1_KlusterList_To_kluster_KlusterList(in, out, s)
}

func autoConvert_kluster_KlusterList_To_v1alpha1_KlusterList(in *kluster.KlusterList, out *KlusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Kluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_kluster_KlusterList_To_v1alpha1_KlusterList is an autogenerated conversion function.
func Convert_kluster_KlusterList_To_v1alpha1_KlusterList(in *kluster.KlusterList, out *KlusterList, s conversion.Scope) error {
	return autoConvert_kluster_KlusterList_To_v1alpha1_KlusterList(in, out, s)
}

func autoConvert_v1alpha1_KlusterSpec_To_kluster_KlusterSpec(in *KlusterSpec, out *kluster.KlusterSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Region = in.Region
	out.Version = in.Version
	out.TokenSecret = in.TokenSecret
	out.NodePools = *(*[]kluster.NodePool)(unsafe.Pointer(&in.NodePools))
	return nil
}

// Convert_v1alpha1_KlusterSpec_To_kluster_KlusterSpec is an autogenerated conversion function.
func Convert_v1alpha1_KlusterSpec_To_kluster_KlusterSpec(in *KlusterSpec, out *kluster.KlusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_KlusterSpec_To_kluster_KlusterSpec(in, out, s)
}

func autoConvert_kluster_KlusterSpec_To_v1alpha1_KlusterSpec(in *kluster.KlusterSpec, out *KlusterSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Region = in.Region
	out.Version = in.Version
	out.TokenSecret = in.TokenSecret
	out.NodePools = *(*[]NodePool)(unsafe.Pointer(&in.NodePools))
	return nil
}

// Convert_kluster_KlusterSpec_To_v1alpha1_KlusterSpec is an autogenerated conversion function.
func Convert_kluster_KlusterSpec_To_v1alpha1_KlusterSpec(in *kluster.KlusterSpec, out *KlusterSpec, s conversion.Scope) error {
	return autoConvert_kluster_KlusterSpec_To_v1alpha1_KlusterSpec(in, out, s)
}

func autoConvert_v1alpha1_NodePool_To_kluster_NodePool(in *NodePool, out *kluster.NodePool, s conversion.Scope) error {
	out.Size = in.Size
	out.Name = in.Name
	out.Count = in.Count
	return nil
}

// Convert_v1alpha1_NodePool_To_kluster_NodePool is an autogenerated conversion function.
func Convert_v1alpha1_NodePool_To_kluster_NodePool(in *NodePool, out *kluster.NodePool, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodePool_To_kluster_NodePool(in, out, s)
}

func autoConvert_kluster_NodePool_To_v1alpha1_NodePool(in *kluster.NodePool, out *NodePool, s conversion.Scope) error {
	out.Size = in.Size
	out.Name = in.Name
	out.Count = in.Count
	return nil
}

// Convert_kluster_NodePool_To_v1alpha1_NodePool is an autogenerated conversion function.
func Convert_kluster_NodePool_To_v1alpha1_NodePool(in *kluster.NodePool, out *NodePool, s conversion.Scope) error {
	return autoConvert_kluster_NodePool_To_v1alpha1_NodePool(in, out, s)
}
